name: Deploy to sfsb environment on push to main

on:
  push:
    branches: [ main ]
    paths:
      - 'force-app/**'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy-to-sfsb-environment:
    runs-on: ubuntu-latest
    environment: SANDBOX

    steps:
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Install sfdx-git-delta
        run: |
          echo Y | sf plugins install sfdx-git-delta
          sf plugins
          sf version --verbose

      # Create delta packages WITH manifest (package.xml)
      
      - name: Create delta packages
        run: |
          mkdir -p changed-sources
          sf sgd source delta \
            --to "HEAD" \
            --from "HEAD~1" \
            --output-dir "changed-sources" \
            --generate-delta \
            --source-dir "force-app"

          echo "----- Listing changed-sources -----"
          ls -la changed-sources || true
          echo "----- Find generated package.xml -----"
          find changed-sources -name package.xml -print -exec cat {} \; || true

      # Create JWT key file from GitHub secret
      - name: Create JWT key file
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          chmod 600 server.key

      # Debug instance url (helps detect empty vars)
      - name: Debug INSTANCE_URL
        run: |
          echo "SF_INSTANCE_URL='${{ vars.SF_INSTANCE_URL }}'"

      # Authenticate to Salesforce via JWT
      - name: Authenticate to Salesforce (JWT)
        run: |
          sf org login jwt \
            --username "${{ secrets.SF_USER_NAME }}" \
            --jwt-key-file server.key \
            --client-id "${{ secrets.SF_CONSUMER_KEY }}" \
            --instance-url "${{ vars.SF_INSTANCE_URL }}" \
            --set-default

      - name: Debug org connection
        run: |
          sf org display --verbose

      # Deploy using manifest ONLY if package.xml exists


      - name: Deploy delta to Sandbox using Manifest (Run Local Tests)
        if: ${{ hashFiles('changed-sources/package/package.xml') != '' }}
        run: |
          echo "Manifest found. Deploying using package.xml..."
          sf project deploy start \
            --manifest changed-sources/package/package.xml \
            --test-level RunLocalTests \
            --wait 60

      # If no package.xml, skip deploy
      - name: No delta changes - skipping deployment
        if: ${{ hashFiles('changed-sources/package/package.xml') == '' }}
        run: |
          echo "No package.xml found. Skipping deployment."

      # Cleanup always
      - name: Clean up
        if: always()
        run: rm -f server.key
