name: Deploy to sfsb environment on push to main

on:
  push:
    branches: [ main ]
    paths:
      - 'force-app/**'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy-to-sfsb-environment:
    runs-on: ubuntu-latest
    environment: SANDBOX

    steps:
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Install sfdx-git-delta
        run: |
          echo Y | sf plugins install sfdx-git-delta
          sf plugins
          sf version --verbose

      - name: Create delta packages
        run: |
          mkdir -p changed-sources
          sf sgd source delta \
            --to "HEAD" \
            --from "HEAD~1" \
            --output-dir "changed-sources" \
            --generate-delta \
            --source-dir "force-app"
          echo "[INFO] Diff generated"
          find changed-sources -maxdepth 4 -type f | sort || true

      - name: Stop if no Salesforce delta found
        run: |
          if [ ! -d changed-sources/force-app ]; then
            echo "No force-app changes found. Nothing to deploy."
            exit 0
          fi

      - name: Create JWT key file
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          chmod 600 server.key

      - name: Authenticate to Salesforce
        run: |
          sf org login jwt \
            --username "${{ secrets.SF_USER_NAME }}" \
            --jwt-key-file server.key \
            --client-id "${{ secrets.SF_CONSUMER_KEY }}" \
